runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /record
  script: main.app
- url: /
  static_files: src/static/index.html
  upload: src/static/index\.html
- url: /
  static_dir: src/static

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^package.json$
- ^README.md$
- ^fetch_data.py$
- ^requirements.txt$
- ^[^/]*.sh$
- ^node_modules/.*$
- ^scripts/.*$
- ^src/(components|containers)/.*$
- ^src/[^/]*\.js$
- ^experiment_data/.*$
