dependencies:
  - python=2.7
  - numpy=1.12.*
  - scikit-learn=0.18.*
  - pandas=0.20.*
  - matplotlib=2.0.*
  - seaborn=0.7.*
  - nltk=3.2.*
  - python-dateutil=2.6.*
  - ipython
  - flake8
  - pip:
    - algorithmia==1.0.8
    - hacking
